### ISSUE TITLE
blank explorer.html

### ISSUE THREAD

**Issue by dazzag24** [chronakis/speed-monitor-bot#2]
Hi,

Map is not loading correctly.

console has this error:

```
Uncaught SyntaxError: redeclaration of const botConfig
    <anonymous> http://192.168.1.100:8081/explore.js:1
explore.js:1:1
```

I'm pretty sure that I have followed instructions correctly, although I was a bit unsure what type of here app to choose:

- JavaScript
- REST

Thanks

**Comment by chronakis** [comment]
Hi,

Sorry you run into this. The `bot-config.js.template` had an error. I fixed it in the previous commit, about half an hour ago. Now tested in a clean folder and works. Please pull the project and apply the change from the bot `config.js.template` to the `bot-config.js` file.

Line 1:
```
const config = {
```
One before last line:
```
+  module.exports = { config };
```
Thank you

**Comment by chronakis** [comment]
I think I will close this issue. Please reopen, if not fixed. Also probably not relevant any more with the https://speedbot.bikesnbytes.net/
